#!/bin/bash

HOME_PATH="/opt/tiger"
FASTTEXT_NAME=$1
FILTER=$2
TOKENIZE=$3
TRAIN=$4
CONVERT=$5
EVALUATE=$6
NODE_ADDRESS=$7
VARIENT_NAME=$8
LABEL_NAME=$9
PERCENTAGE_THRESHOLD=${10}
HDFS_PATH=${11}
N_NODE=${12}
TRAINING_STEPS=${13}
NODE_RANK=${14}


# 获取当前节点的 ARNOLD_ID
NODE_ID=$ARNOLD_ID

# 检查当前是主节点还是从节点
if [ "$NODE_ID" -eq 0 ]; then
    echo "Running on node 0"
    bash pipeline.sh ${FASTTEXT_NAME} ${FILTER} ${TOKENIZE} ${TRAIN} ${CONVERT} ${EVALUATE} ${NODE_ADDRESS} ${VARIENT_NAME} ${LABEL_NAME} ${PERCENTAGE_THRESHOLD} ${HDFS_PATH} ${N_NODE} ${TRAINING_STEPS}
else
    echo "Running on node $NODE_ID"
    bash pipeline_slave.sh ${FASTTEXT_NAME} ${FILTER} ${TOKENIZE} ${TRAIN} ${CONVERT} ${EVALUATE} ${NODE_ADDRESS} ${VARIENT_NAME} ${LABEL_NAME} ${PERCENTAGE_THRESHOLD} ${HDFS_PATH} ${N_NODE} ${TRAINING_STEPS} ${NODE_ID}
fi